"""
BugHunter - Report Generator
Produces Markdown + HTML vulnerability reports.
"""

import json
import time
from pathlib import Path
from typing import Optional

from rich.console import Console
from rich.panel import Panel

console = Console()

SEV_EMOJI = {
    "critical": "🔴",
    "high":     "🟠",
    "medium":   "🟡",
    "low":      "🔵",
    "info":     "⚪",
}

SEV_ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}


def _sev(f: dict) -> int:
    return SEV_ORDER.get((f.get("severity") or "info").lower(), 5)


def generate_markdown(target: str, findings: list[dict],
                      breach_data: Optional[dict] = None,
                      alive_count: int = 0,
                      subdomain_count: int = 0) -> str:
    ts      = time.strftime("%Y-%m-%d %H:%M UTC", time.gmtime())
    sorted_f = sorted(findings, key=_sev)

    counts = {s: sum(1 for f in findings if (f.get("severity") or "info").lower() == s)
              for s in SEV_ORDER}

    lines = [
        f"# BugHunter Security Report",
        f"",
        f"> **Target:** `{target}`  ",
        f"> **Date:** {ts}  ",
        f"> **Generated by:** BugHunter v1.0 — AI-Augmented Bug Hunter Framework",
        f"",
        f"---",
        f"",
        f"## Executive Summary",
        f"",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Subdomains Discovered | {subdomain_count} |",
        f"| Live Hosts | {alive_count} |",
        f"| Total Findings | {len(findings)} |",
        f"| Critical | {counts['critical']} |",
        f"| High | {counts['high']} |",
        f"| Medium | {counts['medium']} |",
        f"| Low | {counts['low']} |",
        f"",
        f"---",
        f"",
    ]

    # Breach section
    if breach_data:
        lines += [
            f"## Breach Intelligence",
            f"",
            f"```json",
            json.dumps(breach_data, indent=2)[:1000],
            f"```",
            f"",
            f"---",
            f"",
        ]

    # Findings
    lines += [f"## Vulnerability Findings", f""]

    if not sorted_f:
        lines += ["*No confirmed vulnerabilities found.*", ""]
    else:
        for i, f in enumerate(sorted_f, 1):
            sev   = (f.get("severity") or "info").lower()
            emoji = SEV_EMOJI.get(sev, "⚪")
            rep   = {}
            if f.get("report"):
                try:
                    rep = json.loads(f["report"]) if isinstance(f["report"], str) else f["report"]
                except Exception:
                    rep = {}

            lines += [
                f"### {i}. {emoji} {f.get('title', 'Unnamed Finding')}",
                f"",
                f"| Field | Value |",
                f"|-------|-------|",
                f"| **Severity** | `{sev.upper()}` |",
                f"| **Asset** | `{f.get('asset', '?')}` |",
                f"| **Confirmed** | {'✅ Yes' if f.get('confirmed') else '⏳ Pending'} |",
                f"| **CVSS Estimate** | {rep.get('cvss_estimate', 'N/A')} |",
                f"",
            ]

            if rep.get("description"):
                lines += [f"**Description**", f"", rep["description"], f""]

            if rep.get("impact"):
                lines += [f"**Impact**", f"", rep["impact"], f""]

            if rep.get("steps_to_reproduce"):
                lines += [f"**Steps to Reproduce**", f"", rep["steps_to_reproduce"], f""]

            if f.get("curl_poc") or rep.get("curl_poc"):
                poc = f.get("curl_poc") or rep.get("curl_poc")
                lines += [
                    f"**Proof of Concept (curl)**",
                    f"",
                    f"```bash",
                    poc,
                    f"```",
                    f"",
                ]

            if rep.get("remediation"):
                lines += [
                    f"**Remediation**",
                    f"",
                    f"> {rep['remediation']}",
                    f"",
                ]

            lines += [f"---", f""]

    lines += [
        f"## Disclaimer",
        f"",
        f"This report was generated by BugHunter for authorized security testing purposes only.",
        f"All findings should be verified manually before disclosure.",
        f"",
    ]

    return "\n".join(lines)


def generate_html(markdown_content: str, target: str) -> str:
    """Wrap markdown in a clean HTML report with embedded CSS."""
    # Simple markdown → HTML conversion (no deps)
    html_body = markdown_content
    for pattern, repl in [
        (r"^### (.+)$",    r"<h3>\1</h3>"),
        (r"^## (.+)$",     r"<h2>\1</h2>"),
        (r"^# (.+)$",      r"<h1>\1</h1>"),
        (r"\*\*(.+?)\*\*", r"<strong>\1</strong>"),
        (r"`(.+?)`",       r"<code>\1</code>"),
        (r"^> (.+)$",      r"<blockquote>\1</blockquote>"),
        (r"^---$",         r"<hr>"),
    ]:
        import re
        html_body = re.sub(pattern, repl, html_body, flags=re.MULTILINE)

    # Code blocks
    import re
    html_body = re.sub(
        r"```(\w+)?\n(.*?)```",
        r"<pre><code>\2</code></pre>",
        html_body, flags=re.DOTALL
    )

    # Tables (simple)
    def table_replace(m):
        rows = [r.strip() for r in m.group(0).strip().splitlines() if "|" in r and "---" not in r]
        html = "<table>"
        for i, row in enumerate(rows):
            cells = [c.strip() for c in row.strip("|").split("|")]
            tag = "th" if i == 0 else "td"
            html += "<tr>" + "".join(f"<{tag}>{c}</{tag}>" for c in cells) + "</tr>"
        html += "</table>"
        return html

    html_body = re.sub(r"(\|.+\|[\n]?)+", table_replace, html_body)

    # Paragraphs
    html_body = re.sub(r"\n\n+", "</p><p>", html_body)
    html_body = f"<p>{html_body}</p>"

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>BugHunter Report — {target}</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: 'Segoe UI', system-ui, sans-serif; background: #0d1117; color: #c9d1d9;
          line-height: 1.6; padding: 2rem; }}
  .container {{ max-width: 900px; margin: 0 auto; }}
  h1 {{ font-size: 2rem; color: #58a6ff; border-bottom: 2px solid #30363d; padding-bottom: .5rem; margin: 1.5rem 0 1rem; }}
  h2 {{ font-size: 1.4rem; color: #79c0ff; margin: 1.5rem 0 .8rem; border-left: 4px solid #388bfd; padding-left: .8rem; }}
  h3 {{ font-size: 1.1rem; color: #ffa657; margin: 1.2rem 0 .6rem; }}
  p {{ margin: .6rem 0; }}
  table {{ width: 100%; border-collapse: collapse; margin: 1rem 0; font-size: .9rem; }}
  th {{ background: #161b22; color: #58a6ff; padding: .5rem .8rem; border: 1px solid #30363d; text-align: left; }}
  td {{ padding: .5rem .8rem; border: 1px solid #30363d; }}
  tr:nth-child(even) {{ background: #161b22; }}
  code {{ background: #161b22; padding: .1rem .4rem; border-radius: 4px; font-family: monospace; font-size: .85rem; color: #e6edf3; }}
  pre {{ background: #161b22; border: 1px solid #30363d; border-radius: 8px; padding: 1rem; overflow-x: auto; margin: .8rem 0; }}
  pre code {{ background: none; padding: 0; }}
  blockquote {{ border-left: 4px solid #3fb950; padding: .4rem 1rem; color: #8b949e; margin: .8rem 0; background: #161b22; border-radius: 0 4px 4px 0; }}
  hr {{ border: none; border-top: 1px solid #30363d; margin: 1.5rem 0; }}
  strong {{ color: #e6edf3; }}
  .header-badge {{ display: inline-block; background: #21262d; border: 1px solid #30363d;
                   border-radius: 20px; padding: .3rem .8rem; font-size: .8rem; color: #8b949e; margin: .5rem .3rem 0 0; }}
</style>
</head>
<body>
<div class="container">
{html_body}
</div>
</body>
</html>"""


def save_report(target: str, findings: list[dict], reports_dir: Path,
                breach_data: Optional[dict] = None,
                alive_count: int = 0, subdomain_count: int = 0) -> tuple[Path, Path]:
    """Generate and save both Markdown and HTML reports."""
    reports_dir.mkdir(parents=True, exist_ok=True)
    slug = target.replace(".", "_").replace("/", "_")
    ts   = time.strftime("%Y%m%d_%H%M%S")

    md_path   = reports_dir / f"{slug}_{ts}.md"
    html_path = reports_dir / f"{slug}_{ts}.html"

    md_content = generate_markdown(target, findings, breach_data, alive_count, subdomain_count)
    md_path.write_text(md_content)

    html_path.write_text(generate_html(md_content, target))

    console.print(Panel(
        f"[bold green]  Reports saved:[/bold green]\n\n"
        f"  [cyan]Markdown:[/cyan] {md_path}\n"
        f"  [cyan]HTML:[/cyan]     {html_path}",
        border_style="green",
        title="[bold]Report Generated[/bold]",
    ))

    return md_path, html_path
